Sprint 2
orlovse/middle.messenger.praktikum.yandex pull request #2
Opened 2021-06-13 18:28 UTC by orlovse

1. Переделал функционал моего шаблонизатора, принцип его работы подробнее опишу в readme в ветке main.
Сейчас есть возможность добавлять события + реактивные данные, при изменении которых происходит перерендер родителя, плюс есть опция указать, что ререндер не требуется.
Очень хотелось написать всё в функциональном стиле, поэтому не пользовался кодом из теоретической части, а написал всё сам. Конечно есть косяки, но надеюсь поправимые =)

2. Перевёл проект на TypeScript, местами есть any, которые надо обдумать и правильно прописать

3. Добавил eslint, stylelint

4. Добавил валидацию интупов по заданным правилам +  при сабмите проверка всех правил формы.

5. Из дополнительных мелочей - поправил кое где стили, добавил возможность переключаться между светлой/темной темой. Кнопка переключения пока что просто див с текстом, даже без поинтера по ховеру, тк это временная кнопка, потом поменяю на тоггл.

2021-06-14 14:25 UTC, DmitryKhitrin commented on .eslintignore
> +/.github
[EOF](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline)

2021-06-14 15:31 UTC, DmitryKhitrin requested changes
Привет, спасибо за вашу работу, все выглядит очень лаконично)

По поводу пунктов из ТЗ:

- Работа выполнена в функциональном стиле, так что кажется, базовый компонент тут не применим, это верно;
- EventBus, его все же можно было бы реализовать, что бы упросить работу с глобальными ивентами приложения;
- Отсутствует реализация класса для работы с запросами;

2021-06-14 15:31 UTC, khitrind commented on .eslintrc.json
> +}
[EOF](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline)

2021-06-14 15:31 UTC, khitrind commented on src/components/_boilerplate/component.ts
> +  const template = `
Я думаю, что будет лучше вынести объявление темплейта за пределы функции, так мы будем создавать эту переменную всего один раз, а не на каждый вызов

2021-06-14 15:31 UTC, khitrind commented on src/components/_boilerplate/component.ts
> +export default Component;
Часто именованные импорты получаются гораздо удобней дефолтных, так мы гораздо лучше понимаем, что именно экспортируется из модуля)

2021-06-14 15:31 UTC, khitrind commented on src/pages/login/login.scss
> +    // opacity: 0;
Закомментированный код лучше либо удалять, либо оставлять комментарий зачем он здесь в таком виде находится)

2021-06-14 15:31 UTC, khitrind commented on src/utils/index.ts
> +  for (let key of keys) {
Модифицирую внешние переменные всегда велик шанс запутаться, так что тут, вместо обычного цикла я бы предложил использовать [reduce](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce)

2021-06-14 15:31 UTC, khitrind commented on src/utils/index.ts
> +export const checkValid = (rules: ValidationRules, value: string | number) => {
Вместо одной функции проверяющей на все, я бы предложил создать несколько маленьких, проверяющих на что-то одно и хранить их в условном словаре: `Record<Type, Rule>`. Тогда и checkValid упростится, так как на вход у нее будет только type и value, а вся логика будет в простом применение правила к значению)

Так же такой набор атомарных функций, гораздо проще тестировать + типы будут защищать, от вызова с каким-то неизвестным типом валидатора)

2021-06-14 15:31 UTC, DmitryKhitrin commented on src/utils/regex.ts
> +export const emailRegExp = /\S+@\S+\.\S+/;
Данная регулярное выражение для проверки почты не совсем корректно, к примеру вот такой вариант проходит валидацию `asd@@@@ad....ru`

Нет ничего плохого что бы заимствовать какие-то общие решения) Регулярки для валидации почты написали, [уже 100000 раз](https://emailregex.com/)) Так что можно взять уже готовую, написав в комментарии ссылку на источник, что бы потом было проще дебажить.

2021-06-14 15:31 UTC, DmitryKhitrin commented on src/template/index.ts
> +      events.map(({ selector, event, func }) => {
Тут лучше подойдет forEach, а не map, так как нам не нужно возвращаемое значение

2021-06-14 15:31 UTC, DmitryKhitrin commented on src/components/input/input.ts
> +  const rData = reactivData({
Пока не очень поймал смысл модуля reactiveData, ведь эта функция выполняется на каждый вызов рендера, на каждый вызов генерит id, получается - это просто общий интерфейс для работы с данными? Почему тогда reactive?

2021-06-14 15:31 UTC, DmitryKhitrin commented on src/components/registration/registration.ts
> +        if (isValid) {
Я так понимаю, при успешной регистрации, не предусмотрен переход на страницу приложения или же обратно к логину?

2021-06-14 17:33 UTC, orlovse commented on .eslintignore
> +/.github
Не знал, спасибо, исправил! =)

2021-06-14 17:34 UTC, orlovse commented on src/components/_boilerplate/component.ts
> +  const template = `
Ага, вынес

2021-06-14 17:34 UTC, orlovse commented on src/components/_boilerplate/component.ts
> +export default Component;
Исправил импорты)

2021-06-14 17:34 UTC, orlovse commented on src/pages/login/login.scss
> +    // opacity: 0;
Удалил

2021-06-14 17:41 UTC, orlovse commented on src/utils/index.ts
> +  for (let key of keys) {
Да, с редьюсом получилось короче и красивее, не подумал сразу, спасибо!

2021-06-14 17:43 UTC, orlovse commented on src/utils/index.ts
> +export const checkValid = (rules: ValidationRules, value: string | number) => {
Я изначально исходил из логики, что туда можно передать сразу массив из нескольких правил и типа это удобнее, но вероятно в данном проекте и не будет необходимости кидать сразу много правил на одно поле. В общем надо бы поправить, но можно уже к следующему спринту? =)

2021-06-14 17:43 UTC, orlovse commented on src/utils/regex.ts
> +export const emailRegExp = /\S+@\S+\.\S+/;
Ага, исправил

2021-06-14 17:44 UTC, orlovse commented on src/template/index.ts
> +      events.map(({ selector, event, func }) => {
Исправил)

2021-06-14 17:44 UTC, orlovse commented on src/components/input/input.ts
> +  const rData = reactivData({
А там при использовании set() происходит ререндер компонента)

2021-06-14 17:47 UTC, orlovse commented on src/components/registration/registration.ts
> +        if (isValid) {
Добавил переход на страницу с чатами если поля валидны.  Долго искал, но нашёл такой интересный способ следить за обновлениями в url строке браузера https://itsopensource.com/how-to-call-a-function-on-URL-change-in-javascript/

Так что я чуть изменил роутинг пока что, вынес маунт из роутинга в эту странную функцию, которая срабатывает при изменении адреса. Но теперь есть смысл вообще изменить роутинг, это уже в следующем спринте

2021-06-14 17:49 UTC, orlovse commented on .eslintrc.json
> +}
> * Работа выполнена в функциональном стиле, так что кажется, базовый компонент тут не применим, это верно;
> * EventBus, его все же можно было бы реализовать, что бы упросить работу с глобальными ивентами приложения;
> * Отсутствует реализация класса для работы с запросами;

Спасибо за ревью, очень круто было! =)
Эти пункты уже не сегодня..

2021-06-15 05:36 UTC, orlovse commented on .eslintrc.json
> +}
Добавил класс для работы с запросами, использовал то, что делал в тренажёре теоретической части, переделав на TS

2021-06-15 06:40 UTC, orlovse commented on .eslintrc.json
> +}
На счёт шины событий.. сейчас я добавляю события на конкретный html элемент при его создании. Получается, что когда я монтирую элемент - это событие работает на нём, когда элемента в дом дереве нет, то и события не существует же, тк оно не было навешено на document?
Пока что у меня есть одно глобальное событие, которое следит за всеми кликами и если это <a>, то направляет по ссылке, но по большому счёту нет случаев, когда это событие нужно отключать. Я только думаю в будущем это событие убрать вообще, но создать компонент линк, на котором будет висеть это событие, чтобы не слушать всё приложение. 
В общем если можно, я бы пока что не стал реализовывать шину событий, на на следующих этапах внедрю её. Так то у нас есть готовый класс из теоретической части, просто пока не знаю как её использовать в моей реализации

2021-06-15 07:28 UTC, DmitryKhitrin commented on src/core/fetch.ts
> +    return `${result}${key}=${data[key]}${index < keys.length - 1 ? "&" : ""}`;
Можн еще как-то так:

Object.entries(data).reduce((result, [key, data]) => `${result}&${key}=${data}`, '?');

2021-06-15 07:29 UTC, DmitryKhitrin commented on src/core/fetch.ts
> +function queryStringify(data: Object) {
Тут тип скорее Record<string, any>

2021-06-15 07:30 UTC, DmitryKhitrin commented on src/core/fetch.ts
> +      xhr.open(method, isGet && !!data ? `${url}${queryStringify(data)}` : url);
Лучше использовать явное преобразование, Boolean, так код немного проще читается

2021-06-15 07:32 UTC, DmitryKhitrin commented on src/core/fetch.ts
> +      xhr.open(method, isGet && !!data ? `${url}${queryStringify(data)}` : url);
Что бы не заводить в общем методе флажок isGet, можно формировать url с query сразу в методе get

2021-06-15 07:32 UTC, DmitryKhitrin approved these changes
Супер, спасибо за внесенные правки и удачи в следующем спринте!)

2021-06-15 07:53 UTC, merged